### ISSUE TITLE
taxi_system example not working

### ISSUE THREAD

**Issue by joegoggins** [paddor/cztop#1]
Hi there,

The taxi system example is a great use case to demonstrate the fanciness of this tool, however, it appears that it's not working or I'm doing something wrong.

Given that I've run `generate_keys.sh`
And I've started the the broker
And started the clients
When I run `send_command("driver1", "PICKUP(8.541694,47.376887)")`
I get `Driver "driver1" has never connected`

The broker never gets past line 43, and never says "socket is readable".
I got the same behavior on Ruby 2.3.0 and 2.2.3. OS X installed with `--HEAD` flag with libsodium with homebrew.

Let me know if I can provide more details.

Thanks,

-joe

**Comment by paddor** [comment]
Thanks for reporting this. Looks like the poller used inside the broker doesn't get the event.

I'm trying to get the test suite back to working again here but just noticed CZMQ HEAD has changed quite a bit. I need to update czmq-ffi-gen first, fix zarmour (the decoding changed), and then I can hopefully fix it.

**Comment by paddor** [comment]
Just released czmq-ffi-gen 0.8.0. It'll only work with CZMQ built from master from now on. Its test suite is happy. CZTop's test suite is also happy now. Don't know why the poller in this examle won't receive the event that the socket is readable right now.

**Comment by paddor** [comment]
Running the broker with `$DEBUG = true` and also a new test case in CZTop::Poller's specs tell me that calling `#wait` will cause the low-level call to fail with EINVAL (which is converted to an ArgumentError by CZTop in Ruby). Apparently this only happens with SERVER (and maybe CLIENT) sockets. As far as I can remember, this used to work (at least for polling for reading, which is the case here). Maybe something changed in ZMQ.

**Comment by paddor** [comment]
Now it should work. :)

**Comment by joegoggins** [comment]
Cheers @paddor , great work! It's so awesome to see this kind of testing and documentation quality in a Gem I'm leaning on heavily in a complex upstream project--makes me smile, thanks for that yo, much appreciated.

**Comment by paddor** [comment]
Very much appreciated! 100% test coverage (well, complete _specs_) and hight documentation quality were my top goals. :-)
