### ISSUE TITLE
Install problem on Windows with 0.13.x

### ISSUE THREAD

**Issue by jmarrec** [paddor/cztop#17]
It seems that I cannot install correctly cztop 0.13.0 nor 0.13.1 on Windows with Ruby 2.2.6. It works when I install cztop 0.12.2 though. 

I found that out via this issue I opened on iRuby: https://github.com/SciRuby/iruby/issues/148
You can find my detailed system information in this linked issue.

When I require cztop, it seems to be looking for Unix paths instead of Windows.

Here's what I get for 0.13.0 (or 0.13.1 for that matter):

```
(base) C:\Users\julien>gem install cztop -v 0.13.0
Fetching: ffi-1.9.23-x64-mingw32.gem (100%)
Successfully installed ffi-1.9.23-x64-mingw32
Fetching: czmq-ffi-gen-0.15.0.gem (100%)
Successfully installed czmq-ffi-gen-0.15.0
Fetching: cztop-0.13.0.gem (100%)
Successfully installed cztop-0.13.0
Parsing documentation for ffi-1.9.23-x64-mingw32
Installing ri documentation for ffi-1.9.23-x64-mingw32
Parsing documentation for czmq-ffi-gen-0.15.0
Installing ri documentation for czmq-ffi-gen-0.15.0
Parsing documentation for cztop-0.13.0
Installing ri documentation for cztop-0.13.0
Done installing documentation for ffi, czmq-ffi-gen, cztop after 3 seconds
3 gems installed

(base) C:\Users\julien>pry
[1] julien(main)> require 'cztop'

WARNING: ::CZMQ::FFI is not available without libczmq.

LoadError: Could not open library '/usr/local/lib/libzmq.dll': The specified module could not be found.
.
Could not open library '/opt/local/lib/libzmq.dll': The specified module could not be found.
.
Could not open library '/usr/lib64/libzmq.dll': The specified module could not be found.
.
Could not open library 'libzmq': The specified module could not be found.
.
Could not open library 'libzmq.dll': The specified module could not be found.
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.23-x64-mingw32/lib/ffi/library.rb:147:in `block in ffi_lib'
```

**Comment by paddor** [comment]
Thanks for the report. It's possible that something went wrong during the release process of 0.13.x. I honestly don't know much about Windows, and @kou contributed the Windows support.

Is it possible that a PR similar to paddor/czmq-ffi-gen#4 (`LIBZMQ_PATH` environment variable) is needed, but this time for CZMQ's location?

**Comment by kou** [comment]
It seems that czmq-ffi-gen 0.15.0 doesn't provides fat gems for Windows: https://rubygems.org/gems/czmq-ffi-gen/versions
(x86-mingw32 and x64-mingw32 variants for 0.15.0 don't exist.)

@paddor Can you try to upload gems for them?

**Comment by paddor** [comment]
Reviving this repo. Reopen if needed.
