### ISSUE TITLE
Support ztimerset

### ISSUE THREAD

**Issue by washu** [paddor/cztop#18]
https://github.com/zeromq/czmq#ztimerset---timer-set The bindings are being built for czmq, just missing the top level api in cztop for it.

**Comment by paddor** [comment]
Not sure about the use case. Could you use a timer gem for Ruby instead? I have a feeling that the ztimer_set API is meant to ease programming in C.

**Comment by washu** [comment]
would it not offer offloading of the timer code itself to a native thread in the lib instead of the ruby gil stack?

**Comment by paddor** [comment]
You might be right, but I guess if you supply a Ruby block to be executed (probably 99% of the time, instead of a pointer to a C function), it will still be the Ruby thread who runs it when fired. I might be wrong. 

You're welcome to send a PR.

**Comment by paddor** [comment]
Reviving this repo. Reopen if needed.
