### ISSUE TITLE
Assertion failed: (!s_process_ctx), function zsys_init, file src/zsys.c, line 182. Abort trap: 6

### ISSUE THREAD

**Issue by joegoggins** [paddor/cztop#3]
I've been getting this failure about every 1 in 5 runs of a multi-threaded program I'm writing. It occurs whether I'm using CURVE_server/client or not. I'm using PUSH/PULL sockets. I'm wondering what would be most useful to provide to illustrate the issue or if you have any recommendations.

Thanks,

-joe

**Comment by paddor** [comment]
Sounds like a race condition within CZMQ's code. Out of curiosity, what system and Ruby/Ruby version are you using? I've ran into quite a few different assertion failures from CZMQ when developing CZTop. But not this one.

**Comment by joegoggins** [comment]
I see the same behavior on:
- `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]`
- `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`

I built zmq, czmq, and libsodium like:

```
    brew update
    brew install libsodium
    brew install zmq  --with-libsodium --HEAD
    brew install czmq --HEAD
```

After a closer inspection of the [czmq code behind that error](https://github.com/zeromq/czmq/blob/master/src/zsys.c#L182-L187) and reading the docs at the top of the [`zsys_init` function in which the error occurs](https://github.com/zeromq/czmq/blob/master/src/zsys.c#L114-L122) I think the likely culprit is that I'm using thread unsafe code wrongly. I'm currently creating, connecting or binding, and making CURVE calls in separate threads. I'll try moving this out of the thread and see if it makes my problem go away... _stay tuned_ :smile:

**Comment by joegoggins** [comment]
Indeed, 'twas an error on my part. Moving instantiation, connect/bind, and `CURVE` calls of `CZTop::Socket::PULL` and friends into the main thread made the problem go away. Closing issue.

**Comment by paddor** [comment]
Glad to hear that! :)
