### ISSUE TITLE
Reimplement CZTop::Poller on top of zmq_poller_*()

### ISSUE THREAD

**Issue by paddor** [paddor/cztop#4]
### Pros
- it'll work with SERVER/CLIENT ("thread-safe") sockets as well
### Cons
- it'll only work on ZMQ >= 4.2
- needs manual loop to get events from all registered sockets to build up an array of interesting sockets
  - in Ruby this might be slow
  - in ZMQ itself this might annoy other people

Solving this issue will help #1.

**Comment by joegoggins** [comment]
:+1: :beers: to solving hard problems!

> it'll only work on ZMQ >= 4.2

This Gem is the new guy on the scene and I think most people are willing to build using HEAD or the latest tagged release. Plus as an author, it might be nice to drop the baggage of supporting older versions.

> it'll work with SERVER/CLIENT ("thread-safe") sockets as well

I read somewhere in one of the ZMQ RFCs that the SERVER/CLIENT is going to the be the goto default or replacement for rep/req as zmq matures. I'm not sure I understand the key advantages that these socket types have over rep/req and the role that the CZTop::Poller has in this pattern. If you have insights here, I'd love to hear them.

**Comment by paddor** [comment]
Thanks.

> This Gem is the new guy on the scene and I think most people are willing to build using HEAD or the latest tagged release. Plus as an author, it might be nice to drop the baggage of supporting older versions.

That's true. But the latest tagged releases of both ZMQ and CZMQ are still not recent enough. I already gave in and decided to drop support for the current release of CZMQ, since the authors told me the current master is pretty different already and they don't plan on releasing anytime soon (unless requested, I think?). As for ZMQ, I settled for 4.1 and 4.2 yesterday (dropped 4.0 support as there's some issue with it when enabling CURVE security in the test suite). But of course, SERVER/CLIENT sockets only work 4.2, as do the `zmq_poller_*()` functions (AFAIK). I don't really mind only supporting >= 4.2. I just thought it would have helped lowering the barrier for users to just give CZTop a try.

> I read somewhere in one of the ZMQ RFCs that the SERVER/CLIENT is going to the be the goto default or replacement for rep/req as zmq matures. I'm not sure I understand the key advantages that these socket types have over rep/req and the role that the CZTop::Poller has in this pattern. If you have insights here, I'd love to hear them.

It's true that it's going to replace ROUTER/DEALER sockets as well as REQ/REP sockets.Key advantage is simplicity, I think. Before, if you wanted to relay a message, its hops were prepended as message parts ("frames") in front of the payload message. AFAIK, now there's a simple, randomly generated 4-byte _routing ID_ which is transient (stays the same when the message is relayed). To send a reply, one sets the same routing ID on the reply message, and it'll be sent along the same path back to its origin. Also, multipart support for messages was dropped for SERVER/CLIENT sockets, as it makes thread-safety impossible and is considered over-engineered anyway. CLIENT sockets are thread-safe, which is new in the ZMQ world. Here's the [formal specification](http://rfc.zeromq.org/spec:41) and here's some [documentation](http://api.zeromq.org/4-2:zmq-socket) about these socket types.

**Comment by joegoggins** [comment]
Cool, thanks for those links--the ZMQ documentation space is so vast, it's easy to misplace or find the thing you're looking for. Say, this is a bit off topic, but I suppose worth asking in relation to the taxi example:

[`CZTop::Monitor.new(@socket)`](https://github.com/paddor/cztop/blob/master/examples/taxi_system/broker.rb#L25-L33) looks powerful. Can you use that to monitor events on a zmq socket running in a remote process or does it need to be within the same process? Can it be used on any zmq socket type?

I want to use [Heartbeating like the taxi example does on push/pull sockets](https://github.com/paddor/cztop/blob/master/examples/taxi_system/broker.rb#L18-L20) but I'm unsure what the expected behavior is when the heartbeat fails, does it raise an exception that I can catch? Also, does heartbeating take away the need for doing manual regular pings?

**Comment by paddor** [comment]
> Can you use that to monitor events on a zmq socket running in a remote process or does it need to be within the same process? Can it be used on any zmq socket type?

The Monitor itself gets the events via a PAIR socket, which works within the same process only. But you could just relay those events to a remote socket, either in a manual loop or maybe even using CZTop::Proxy. What's the use case? Read [here](http://api.zeromq.org/czmq3-0:zmonitor).

AFAIK it just disconnects in case either side doesn't hear anything from the other side for too long (whether it's normal traffic or the automatic periodic pings). What I know is that the serverish socket will generate a DISCONNECT event (in case you're monitoring it). Whether it will raise an exception when you try to send a message via a disconnected socket depends on the socket type. Some of them just drop (like ROUTER), some block. If you set the `sndtimeo`, they'll raise after the timeout expired. I just tested it with a SERVER/CLIENT socket. When the client socket is disconnected and the server socket tries to send a message, it raises `IO::EAGAINWaitWritable` after the set timeout expired. Read more [here](http://api.zeromq.org/4-2:zmq-socket).

**Comment by joegoggins** [comment]
Thanks so much for context and links, very useful. It'll probably be a while before I take advantage of this info to utilize heartbeating and monitoring in my app, but when I do, I'll post my findings and approach here.
