### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by chuckremes** [paddor/cztop#7]
This morning I started to replace my gem `ffi-rzmq` in the `celluloid-zmq` gem with `rbczmq`. Then @digitalextremist pointed me to your repository.

Interested in collaborating on this work?

If so, I think @digitalextremist could invite you into our chatrooms on slack where we are doing a lot of celluloid work. Let one of us know. Thanks!

**Comment by paddor** [comment]
Definitely! It was actually the incentive to get me started. I wanted to port celluloid-zmq on this. There's still an issue hanging on this. @digitalextremist knows which one. 

Sorry for this short answer. Traveling right now. :)

Regards,
Patrik

**Comment by digitalextremist** [comment]
@paddor do you mind refreshing my memory?

You can both count me as at your service on this.

**Comment by chuckremes** [comment]
@paddor @digitalextremist Great, I would love to build on your work. I haven't had a chance to play with the code yet so I should probably carve out some time to run the examples.

Based on a quick code review, you have already done so much work. Integration ought to be a snap. :)

**Comment by paddor** [comment]
@digitalextremist [This](https://github.com/celluloid/celluloid-zmq/issues/56) is the issue I was talking about. 

@chuckremes Thanks! I hope it'll be pretty straight forward. :)

**Comment by chuckremes** [comment]
Just merged the PR. This project is now THE major component of celluloid-zmq.
